#ifndef PYBASIC_BYTECODE_INSTRUCTIONS
#define PYBASIC_BYTECODE_INSTRUCTIONS

enum BYTECODE {
    _INS_RETURN,
    _INS_LABEL_INT,
    _INS_STORE,
    _INS_LOAD_CONST,
    _INS_LOAD_GLOBL,
    _INS_BUILD_STR,
    _INS_GOTO,
    _INS_PRINT,
};

#endif
